version: '3'

services:

  wordpress:
    image: wordpress:6.4.3
    container_name: uniformeescolar
    restart: unless-stopped
    environment:
      - WORDPRESS_DEBUG=0
      - WORDPRESS_DB_HOST=host.docker.internal:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=Mudar*140418
      - WORDPRESS_DB_NAME=uniformeescolar
    volumes:
        - ./wp-content:/var/www/html/wp-content
    extra_hosts:
        - "host.docker.internal:host-gateway"
    ports:
      - "50045:80"
